### ISSUE TITLE
GenericCurveEditor images are broken in readme

### ISSUE THREAD

**Issue by hannesdelbeke** [EpicKiwi/unreal-engine-editor-icons#1]

**Comment by EpicKiwi** [comment]
Thank's for the report. I'm not currently into Unreal Engine and don't have time to update the repository.

If you feel comfortable with Unreal codebase you can find icon definition into it. The way I extracted icons are defined in [first paragraph of Readme](https://github.com/EpicKiwi/unreal-engine-editor-icons#where-are-icons-defined-). Pull requests are welcome  :)

**Comment by hannesdelbeke** [comment]
No worries, I've made [a little tool](https://github.com/hannesdelbeke/texture-browser-unreal-plugin) to extract the images from the unreal installation folder instead. And let the user run this inside of Unreal. so it will stay up to date.
And linked your repo at the bottom in `similar projects`.
<img src="https://github.com/hannesdelbeke/texture-browser-unreal-plugin/assets/3758308/29b35d56-da78-4263-b8bb-08c24c072ae9" width="300"/>

**Comment by EpicKiwi** [comment]
Nice ! Thank you for your tool. I added your tool to readme's header. I close for now as "Won't fix"
